# Generated by Django 3.1.6 on 2021-02-09 07:31

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('sku', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.helpers.RandomFileName('img/'))),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
